HotelAssignment/Models/Domain/HotelData.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace HotelAssignment.Models.Domain
{
    public class HotelData
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string? Name { get; set; }
        [Required]
        [EmailAddress]
        public string? Email { get; set; }
        [Required]
        public string? Address { get; set; }

        public string Path { get; set; }

        [NotMapped]
        public IFormFile ImagePath { get; set; }
    }
}

HotelAssignment/Models/ErrorViewModel.cs
namespace HotelAssignment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HotelAssignment/Models/HotelModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HotelAssignment.Models
{
    public class HotelModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string? Name { get; set; }
        [Required]
        [EmailAddress]
        public string? Email { get; set; }
        [Required]
        public string? Address { get; set; }

        public string Path { get; set; }

        [NotMapped]
        public IFormFile ImagePath{ get; set; }
    }
}

HotelAssignment/Controllers/HomeController.cs
using HotelAssignment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HotelAssignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HotelAssignment/Controllers/HotelController.cs
using HotelAssignment.Data;
using HotelAssignment.Models;
using HotelAssignment.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HotelAssignment.Controllers
{
    public class HotelController : Controller
    {
        private readonly HotelDbContext _db;
        private readonly IWebHostEnvironment environment;
        public HotelController(HotelDbContext _db, IWebHostEnvironment environment)
        {
            this._db = _db;
            this.environment = environment;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var hotel = await _db.HotelData.ToListAsync();
            return View(hotel);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Add(HotelModel model)
        {
            string uniqueFileName = UploadImage(model);
            var hotel = new HotelData()
            {
                Name = model.Name,
                Address = model.Address,
                Email = model.Email,
                Path = uniqueFileName,
                // Image = model.Image,

            };
            await _db.HotelData.AddAsync(hotel);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private string UploadImage(HotelModel model)
        {
            string uniqueFileName = "";
            if (model.ImagePath!=null)
            {
                string uploadFolder = Path.Combine(environment.WebRootPath, "image");
                 uniqueFileName=Guid.NewGuid().ToString() + "_"+ model.ImagePath.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ImagePath.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
        [HttpGet]
        public async Task<IActionResult> Update(int Id)
        {
            var data = await _db.HotelData.FirstOrDefaultAsync(x => x.Id == Id);
            if (data != null)
            {
                var model = new HotelModel()
                {
                    Id = data.Id,
                    Name = data.Name,
                    Address = data.Address,
                    Email = data.Email,
                    Path = data.Path,

                };
                return await Task.Run(() => View("Update", model));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Update(HotelModel model)
        
        
            {
            var result = await _db.HotelData.FindAsync(model.Id);
            string uniqueFileName = string.Empty;
            if (model.ImagePath != null)
            {
                if (result.Path != null)
                {
                    string filepath = Path.Combine(environment.WebRootPath, "image", result.Path);
                    if (System.IO.File.Exists(filepath))
                    {
                        System.IO.File.Delete(filepath);
                    }
                }
                uniqueFileName = UploadImage(model);
            }
            if(model.ImagePath!=null)
            {
  
            }
                if (result != null)
                {
                    result.Id = model.Id;
                    result.Name = model.Name;
                    result.Address = model.Address;
                    result.Email = model.Email;
                    result.Path = uniqueFileName;
                await _db.SaveChangesAsync();


                }
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> ProfileDetail(int Id)
        {
            var data = await _db.HotelData.FirstOrDefaultAsync(x => x.Id == Id);
            if (data != null)
            {
                var model = new HotelModel()
                {
                    Id = data.Id,
                    Name = data.Name,
                    Address = data.Address,
                    Email = data.Email,
                    Path = data.Path,

                };
                return await Task.Run(() => View("ProfileDetail", model));
            }
            return RedirectToAction("Index");

        }

        [HttpPost]

        public async Task<IActionResult> Delete(int Id)
        {
            var res = await _db.HotelData.Where(x => x.Id == Id).SingleOrDefaultAsync(); 
            if (res != null)
            {
                string deleteFromFolder = Path.Combine(environment.WebRootPath, "image");
                string currentImage = Path.Combine(Directory.GetCurrentDirectory(), deleteFromFolder, res.Path);
                if (currentImage !=null)
                {
                    if (System.IO.File.Exists(currentImage))
                    {
                        System.IO.File.Delete(currentImage);    
                    }
                }
                _db.HotelData.Remove(res);
                await _db.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }


    }
}

HotelAssignment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HotelAssignment/Views/Hotel/Add.cshtml
@model HotelAssignment.Models.HotelModel
@{
}
<div class="container my-auto">
    <div class="row my-5">
    
        <div class="col-lg-5 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">

                            <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Add</h4>

                    </div>
                </div>
                <div class="card-body">
                    <form method="post" role="form" asp-action="Add" enctype="multipart/form-data">
                        @Html.ValidationSummary(true)
          
                        <div class="input-group input-group-outline my-3 ">
                            <label class="form-label"></label>
                            <input type="text" asp-for="Name" placeholder="Name" class="form-control" required>
                            <br />
                            <span>@Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })</span>

                        </div>


                        <div class="input-group input-group-outline my-3 ">
                            <label class="form-label"></label>
                            <input type="email" asp-for="Email" placeholder="Email" class="form-control" required>
                            <br />
                            <span>@Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })</span>

                        </div>




                        <div class="input-group input-group-outline my-3 ">
                            <label class="form-label"></label>
                            <input type="text" asp-for="Address" class="form-control" placeholder="Address" required>
                            <br />
                            <span>@Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })</span>

                        </div>
                        <div class="input-group input-group-outline my-3 row">
                          <div class="col-9">  
                              <label class="form-label"></label>
                            <input type="file" asp-for="ImagePath" class="form-control" id="chooseImg" required>
                            </div>
                            <div class="col-3">
                                <img src="https://placehold.jp/150*150.png" id="imgPreview" style="width:70px; height:70px; border:1px solid red; border-radius:10px; padding:5px;" alt="Laptop image" />
                            </div>
                            <br />
                            <span>@Html.ValidationMessageFor(m => m.ImagePath, "", new { @class = "text-danger" })</span>

                        </div>


                    
                 
           
                            <button type="submit" class="btn btn-lg bg-gradient-secondary btn-lg w-100 mt-4 mb-0">Submit</button>

                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

                            @section scripts{
                                <script src ="~/js/JavaScript.js">
                                   </script>
                            };

HotelAssignment/Views/Hotel/Index.cshtml
@model List<HotelAssignment.Models.Domain.HotelData>
;

    <div class="row">
        <div class="col-12">
            <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                        <h6 class="text-white text-capitalize ps-3">Hotel List</h6>
                    </div>
                </div>
                <div class="card-body px-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0">
                            <thead>
                                <tr>
                                <th class="text-uppercase text-dark text-2xl font-weight-bolder font opacity-7">S.N</th>

                                <th class="text-uppercase text-dark text-2xl font-weight-bolder font opacity-7">Name</th>
                                <th class="text-uppercase text-dark text-2xl font-weight-bolder opacity-7 ps-2">Email</th>
                                <th class="text-uppercase text-dark text-2xl font-weight-bolder opacity-7 ps-2">Address</th>
                                <th class="text-uppercase text-dark text-2xl font-weight-bolder opacity-7 ps-2">Image</th>
                                <th class="text-uppercase text-dark text-2xl font-weight-bolder opacity-7 ps-2">Action</th>

                            </tr>

                            </thead>
                            <tbody>
                                @foreach (var data in Model)
                                {
                                var imagePath = "../image/" + data.Path;
                                <tr>
                                    <td class="text-xl text-dark mb-0">
                                        @data.Id
                                    </td>
                                    <td class="text-xl text-dark mb-0">
                                        <div class="d-flex flex-column justify-content-center">
                                            <h6 class="mb-0 text-sm"><a asp-controller="Hotel" asp-action="ProfileDetail" asp-route-id="@data.Id" >@data.Name</a></h6>
                                           
                                        </div>
                                    </td>
                                  
                                    <td>
                                        <p class="text-xl text-dark mb-0">@data.Address</p>
                                    </td>
                                    <td>
                                        <p class="text-xl text-dark mb-0">@data.Email</p>
                                    </td>
                                    <td>

                                        <img src="../image/@Html.DisplayFor(modelItem => data.Path)" height="100px;" width="100px;" />
                                    </td>
                                    <td>

                                        <a class="text-danger font-weight-bold text-xs" asp-controller="Hotel" asp-action="Delete" asp-route-id="@data.Id">
                                            <i class="material-icons text-sm me-2">delete</i>
                                            Delete
                                        </a>

                                        <a class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit Form" asp-controller="Hotel" asp-action="Update" asp-route-id="@data.Id">
                                            <i class="material-icons text-sm me-2">edit</i>
                                            Edit
                                        </a>
                                    </td>
                                    </tr>
                                    }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

HotelAssignment/Views/Hotel/ProfileDetail.cshtml
@model HotelAssignment.Models.HotelModel;
@{
}

<br />
<br />
<div class="card card-body mx-3 mx-md-4 mt-n6">

    <div class="row">
        <div class="row">
            <div class="col-8" style="border-bottom: 1px solid #f0f2f5;">
                <div class="card card-plain h-100">
                    <div class="card-header pb-0 p-3">
                        <div class="row">
                            <div class="col-md-8 d-flex align-items-center">
                                <h6 class="mb-0 text-2xl">Key Informations</h6>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            <li class="list-group-item border-0 ps-0 pt-0 text-xl"><strong class="text-dark">S.N:</strong> &nbsp; @Model?.Id</li>
                            <li class="list-group-item border-0 ps-0 text-xl"><strong class="text-dark">Hotel Name:</strong> &nbsp;  @Model?.Name</li>
                            <li class="list-group-item border-0 ps-0 text-xl"><strong class="text-dark">Email:</strong> &nbsp; @Model?.Email</li>
                            <li class="list-group-item border-0 ps-0 text-xl"><strong class="text-dark">Address:</strong> &nbsp; @Model?.Address</li>

                           </ul>
                    </div>
                </div>
            </div>
           
            <div class="col-4" style="border-bottom: 1px solid #f0f2f5;">
                <div class="card card-plain h-100 ">
                    <div class="card-body d-flex justify-content-center align-items-center">
                        <ul class="list-group">
                            <img src="/image/@Model?.Path" id="imgPreview" style="width:170px; height:170px; border:1px solid red; border-radius:10px; padding:5px;" alt="Laptop image" />
                        </ul>
                    </div>
                </div>
            </div>
                
         
                <hr />
            </div>


        <a class="btn btn-lg bg-gradient-secondary btn-lg w-100 mt-4 mb-0" asp-controller="Hotel" asp-action="Index">Back To List</a>


           
        </div>
   </div>
</div>

HotelAssignment/Views/Hotel/Update.cshtml
@model HotelAssignment.Models.HotelModel
@{
}
<div class="container my-auto">
    <div class="row my-5">

        <div class="col-lg-5 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">

                        <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Add</h4>

                    </div>
                </div>
                <div class="card-body">
                    <form method="post" role="form" asp-action="Update" enctype="multipart/form-data">
                        @Html.ValidationSummary(true)
                        <input type="hidden" asp-for="Id" />
                        <div class="input-group input-group-outline my-3 ">
                            <label class="form-label"></label>
                            <input type="text" asp-for="Name" placeholder="Name" class="form-control" required>
                            <br />
                            <span>@Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })</span>

                        </div>


                        <div class="input-group input-group-outline my-3 ">
                            <label class="form-label"></label>
                            <input type="email" asp-for="Email" placeholder="Email" class="form-control" required>
                            <br />
                            <span>@Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })</span>

                        </div>




                        <div class="input-group input-group-outline my-3 ">
                            <label class="form-label"></label>
                            <input type="text" asp-for="Address" class="form-control" placeholder="Address" required>
                            <br />
                            <span>@Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })</span>

                        </div>
                        <div class="input-group input-group-outline my-3 row">
                            <div class="col-9">
                                <label class="form-label"></label>
                                <input type="file" asp-for="ImagePath" class="form-control" id="chooseImg" required>
                            </div>
                            <div class="col-3">
                                <img src="/image/@Model.Path" id="imgPreview" style="width:70px; height:70px; border:1px solid red; border-radius:10px; padding:5px;" alt="Laptop image" />
                            </div>
                            <br />
                            <span>@Html.ValidationMessageFor(m => m.ImagePath, "", new { @class = "text-danger" })</span>

                        </div>

                        <button type="submit" class="btn btn-lg bg-gradient-secondary btn-lg w-100 mt-4 mb-0">Submit</button>


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/js/JavaScript.js">
    </script>
};

HotelAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelAssignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HotelAssignment.styles.css" asp-append-version="true" />

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />

    <link href="/assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="/assets/css/nucleo-svg.css" rel="stylesheet" />

    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

    <link id="pagestyle" href="/assets/css/material-dashboard.css?v=3.1.0" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/sweetalert.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/toastr.min.css" rel="stylesheet" />

</head>
<body>
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-info" asp-area="" asp-controller="Home" asp-action="Index">Hotel Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 mx-3 text-center mb-md-0">
                        <li>
                            <a class="nav-link px-2 text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       

                        <li>
                            <a class="nav-link px-2 text-white" asp-area="" asp-controller="Hotel" asp-action="Add">Add New Hotel</a>
                        </li>
                        <li>
                            <a class="nav-link px-2 text-white" asp-area="" asp-controller="Hotel" asp-action="Index">List Hotel</a>
                        </li>

                        <li>
                            <a class="nav-link px-2 text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                </div>
                <div class="text-end">
                    <button type="button" class="btn btn-outline-light me-2">Login</button>
                    <button type="button" class="btn btn-warning">Sign-up</button>
                </div>
            </div>
           
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HotelAssignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>